require "core.comment"
require "core.copilot"
require "core.lsp"
require "core.lualine"
require "core.nvimtree"
require "core.packer"
require "core.remap"
require "core.set"
require "core.telescope"
require "core.treesitter"
require "core.undotree"
-- require "core.vimilluminate"
-- require "core.statuscol"
-- require "core.felinecustom"
-- require "core.feline"
require "core.bufferline"
require "core.cursorline"
-- require "core.gitsigns"
require "core.ufo"
-- require "core.clangd"
require "core.toggleterm"
require "core.nvim-notify"
-- require "core.tabby"
require "core.whichkey"
require "core.autopairs"
require "core.transparent"
require "core.noice"
require "core.symbolsoutline"

vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
